config/routes.rb
Railsconf::Application.routes.draw do

  root :to => "pages#index"
  get "/bohconf", :to => "bohconf_sessions#index"
  get "/boh", :to => "bohconf_sessions#index"
  get "/bohconf_soon", :to => "bohconf_sessions#soon", :as => 'bohconf_sessions_soon'
  get "/boh/:id", :to => "bohconf_sessions#show", :as => "boh_short"
  get "/boh/:id/tweet", :to => "bohconf_sessions#tweet"
  get "/boh/:id/edit", :to => "bohconf_sessions#edit"
  get "/ignite", :to => "pages#ignite"
  get "/talk", :to => "pages#talk"
  get "/stay", :to => "pages#stay"
  get "/5k", :to => "pages#fivek", :as => 'fivek'
  get "/happy", :to => "pages#happy"
  get "/kids", :to => "pages#kids"
  get "/sponsor", :to => "pages#sponsor"
  get "/sponsors", :to => "pages#sponsor"
  get "/usergroups", :to => "pages#usergroups"

  resources :favorites do
    collection do
      get 'thanks'
    end
  end

  resources :guests do
    collection do
      get 'thanks'
    end
  end

  resources :hosts do
    collection do
      get 'thanks'
    end
  end

  resources :speakers do
    collection do
      get 'thanks'
    end
  end

  resources :bohconf_sessions do
    collection do
      get 'thanks'
    end
    member do
      get 'tweet'
      post 'send_tweet'
    end
  end

  resources :twitter_accounts, :only => [:new, :edit, :update] do
    collection do
      get 'callback'
    end
  end
end

app/models/guest.rb
class Guest < ActiveRecord::Base
	validates_presence_of :name, :email, :phone, :bio
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_filter :authenticate, :only => [:index, :edit, :update, :destroy, :show]
  # GET /guests
  # GET /guests.json
  def index
    @guests = Guest.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @guests }
    end
  end

  # GET /guests/1
  # GET /guests/1.json
  def show
    @guest = Guest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @guest }
    end
  end

  # GET /guests/new
  # GET /guests/new.json
  def new
    @guest = Guest.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @guest }
    end
  end

  # GET /guests/1/edit
  def edit
    @guest = Guest.find(params[:id])
  end

  # POST /guests
  # POST /guests.json
  def create
    @guest = Guest.new(params[:guest])

    respond_to do |format|
      if @guest.save
        AdminMailer.submission(@guest).deliver
        format.html { redirect_to thanks_guests_url }
        format.json { render json: @guest, status: :created, location: @guest }
      else
        format.html { render action: "new" }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /guests/1
  # PUT /guests/1.json
  def update
    @guest = Guest.find(params[:id])

    respond_to do |format|
      if @guest.update_attributes(params[:guest])
        format.html { redirect_to @guest, notice: 'Guest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guests/1
  # DELETE /guests/1.json
  def destroy
    @guest = Guest.find(params[:id])
    @guest.destroy

    respond_to do |format|
      format.html { redirect_to guests_url }
      format.json { head :no_content }
    end
  end
end

app/views/guests/_form.html.erb
<%= form_for(@guest) do |f| %>
  <% if @guest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guest.errors.count, "error") %> prohibited this guest from being saved:</h2>

      <ul>
      <% @guest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="span6">
      <div class="control-group">
        <%= f.label :name %>
        <div class="controls">
          <%= f.text_field :name %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :email %>
        <div class="controls">
          <%= f.text_field :email %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :phone %>
        <div class="controls">
          <%= f.text_field :phone %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :twitter %>
        <div class="controls">
          <div class="input-prepend">
            <span class="add-on">@</span>
            <%= f.text_field :twitter, :class => 'span2' %>
          </div>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :bio, 'Tell us a little about yourself.' %>
        <div class="controls">
          <%= f.text_area :bio, :rows => 5 %>
        </div>
      </div>

      <div class="form-actions">
        <%= f.submit 'Submit', :class => 'btn btn-primary' %>
      </div>
    </div>
    <div class="span6">
      <p>Think of it has AirB&B except you'll actually have something in common.</p>
      <p>When we find a host that might be a good match, we'll contact you with their details and give you a chance to vet each other before confirming anything.</p>
    </div>
  </div>
<% end %>

app/views/guests/edit.html.erb
<div class="details">
    <h1>Editing guest</h1>

    <%= render 'form' %>

    <%= link_to 'Show', @guest %> |
    <%= link_to 'Back', guests_path %>
</div>

app/views/guests/index.html.erb
<div class="details">
  <h1>Listing guests</h1>

  <table>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

  <% @guests.each do |guest| %>
    <tr>
      <td><%= guest.name %></td>
      <td><%= guest.email %></td>
      <td><%= guest.phone %></td>
      <td><%= link_to 'Show', guest %></td>
      <td><%= link_to 'Edit', edit_guest_path(guest) %></td>
      <td><%= link_to 'Destroy', guest, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  <% end %>
  </table>

  <br />

  <%= link_to 'New Guest', new_guest_path %>
</div>

app/views/guests/new.html.erb
<div class="details">
    <h1>Apply to stay with a local</h1>

    <%= render 'form' %>
</div>

app/views/guests/show.html.erb
<div class="details">
    <p id="notice"><%= notice %></p>

    <p>
      <b>Name:</b>
      <%= @guest.name %>
    </p>

    <p>
      <b>Email:</b>
      <%= @guest.email %>
    </p>

    <p>
      <b>Phone:</b>
      <%= @guest.phone %>
    </p>


    <%= link_to 'Edit', edit_guest_path(@guest) %> |
    <%= link_to 'Back', guests_path %>
</div>

app/views/guests/thanks.html.erb
<div class="details">
    <h1>Thanks!</h1>

    <p>We'll be in touch soon to work out the details.</p>

    <p>If you have any questions, get in touch with <%= mail_to 'chapambrose@gmail.com' %>.</p>
</div>