config/routes.rb
Railsconf::Application.routes.draw do

  root :to => "pages#index"
  get "/bohconf", :to => "bohconf_sessions#index"
  get "/boh", :to => "bohconf_sessions#index"
  get "/bohconf_soon", :to => "bohconf_sessions#soon", :as => 'bohconf_sessions_soon'
  get "/boh/:id", :to => "bohconf_sessions#show", :as => "boh_short"
  get "/boh/:id/tweet", :to => "bohconf_sessions#tweet"
  get "/boh/:id/edit", :to => "bohconf_sessions#edit"
  get "/ignite", :to => "pages#ignite"
  get "/talk", :to => "pages#talk"
  get "/stay", :to => "pages#stay"
  get "/5k", :to => "pages#fivek", :as => 'fivek'
  get "/happy", :to => "pages#happy"
  get "/kids", :to => "pages#kids"
  get "/sponsor", :to => "pages#sponsor"
  get "/sponsors", :to => "pages#sponsor"
  get "/usergroups", :to => "pages#usergroups"

  resources :favorites do
    collection do
      get 'thanks'
    end
  end

  resources :guests do
    collection do
      get 'thanks'
    end
  end

  resources :hosts do
    collection do
      get 'thanks'
    end
  end

  resources :speakers do
    collection do
      get 'thanks'
    end
  end

  resources :bohconf_sessions do
    collection do
      get 'thanks'
    end
    member do
      get 'tweet'
      post 'send_tweet'
    end
  end

  resources :twitter_accounts, :only => [:new, :edit, :update] do
    collection do
      get 'callback'
    end
  end
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
	validates_presence_of :name, :address, :description

	scope :approved, where(:approved => true)
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_filter :authenticate, :only => [:index, :edit, :update, :destroy]
  # GET /favorites
  # GET /favorites.json
  def index
    @favorites = Favorite.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @favorites }
    end
  end

  # GET /favorites/1
  # GET /favorites/1.json
  def show
    @favorite = Favorite.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @favorite }
    end
  end

  # GET /favorites/new
  # GET /favorites/new.json
  def new
    @favorite = Favorite.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @favorite }
    end
  end

  # GET /favorites/1/edit
  def edit
    @favorite = Favorite.find(params[:id])
  end

  # POST /favorites
  # POST /favorites.json
  def create
    @favorite = Favorite.new(params[:favorite])

    respond_to do |format|
      if @favorite.save
        AdminMailer.submission(@favorite).deliver
        format.html { redirect_to thanks_favorites_url }
        format.json { render json: @favorite, status: :created, location: @favorite }
      else
        format.html { render action: "new" }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /favorites/1
  # PUT /favorites/1.json
  def update
    @favorite = Favorite.find(params[:id])

    respond_to do |format|
      if @favorite.update_attributes(params[:favorite])
        format.html { redirect_to @favorite, notice: 'Favorite was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1
  # DELETE /favorites/1.json
  def destroy
    @favorite = Favorite.find(params[:id])
    @favorite.destroy

    respond_to do |format|
      format.html { redirect_to favorites_url }
      format.json { head :no_content }
    end
  end
end

app/views/favorites/_form.html.erb
<%= form_for(@favorite, :html => {:class => 'form-horizontal'}) do |f| %>
  <% if @favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>

      <ul>
      <% @favorite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name %>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :address %>
    <div class="controls">
      <%= f.text_field :address %>
      <p class="help-block">Street, city, and zip. All on one line, like an animal.</p>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :website %>
    <div class="controls">
      <%= f.text_field :website %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :description %>
    <div class="controls">
      <%= f.text_area :description, :rows => 3 %>
      <p class="help-block">What it is and why is it awesome?</p>
    </div>
  </div>

  <% unless @favorite.new_record? %>
    <div class="control-group">
      <%= f.label :approved %>
      <div class="controls">
        <%= f.check_box :approved %>
      </div>
    </div>
  <% end %>

  <div class="form-actions">
    <%= f.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/favorites/edit.html.erb
<div class="details">
    <h1>Editing favorite</h1>

    <%= render 'form' %>

    <%= link_to 'Show', @favorite %> |
    <%= link_to 'Back', favorites_path %>
</div>

app/views/favorites/index.html.erb
<div class="details">
  <h1>Listing favorites</h1>

  <table>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Website</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

  <% @favorites.each do |favorite| %>
    <tr>
      <td><%= favorite.name %></td>
      <td><%= favorite.address %></td>
      <td><%= favorite.website %></td>
      <td><%= favorite.description %></td>
      <td><%= link_to 'Show', favorite %></td>
      <td><%= link_to 'Edit', edit_favorite_path(favorite) %></td>
      <td><%= link_to 'Destroy', favorite, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  <% end %>
  </table>

  <br />

  <%= link_to 'New Favorite', new_favorite_path %>
</div>

app/views/favorites/new.html.erb
<div class="details">
    <h1>Add a Favorite</h1>

    <%= render 'form' %>
</div>

app/views/favorites/show.html.erb
<div class="details">
    <p id="notice"><%= notice %></p>

    <p>
      <b>Name:</b>
      <%= @favorite.name %>
    </p>

    <p>
      <b>Address:</b>
      <%= @favorite.address %>
    </p>

    <p>
      <b>Website:</b>
      <%= @favorite.website %>
    </p>

    <p>
      <b>Description:</b>
      <%= @favorite.description %>
    </p>


    <%= link_to 'Edit', edit_favorite_path(@favorite) %> |
    <%= link_to 'Back', favorites_path %>
</div>

app/views/favorites/thanks.html.erb
<div class="details">
    <h1>Thanks!</h1>

    <p>We've just been notified and we'll approve your favorite ASAP!</p>

    <p>If you have any questions, get in touch with <%= mail_to 'chapambrose@gmail.com' %>.</p>
</div>