config/routes.rb
Railsconf::Application.routes.draw do

  root :to => "pages#index"
  get "/bohconf", :to => "bohconf_sessions#index"
  get "/boh", :to => "bohconf_sessions#index"
  get "/bohconf_soon", :to => "bohconf_sessions#soon", :as => 'bohconf_sessions_soon'
  get "/boh/:id", :to => "bohconf_sessions#show", :as => "boh_short"
  get "/boh/:id/tweet", :to => "bohconf_sessions#tweet"
  get "/boh/:id/edit", :to => "bohconf_sessions#edit"
  get "/ignite", :to => "pages#ignite"
  get "/talk", :to => "pages#talk"
  get "/stay", :to => "pages#stay"
  get "/5k", :to => "pages#fivek", :as => 'fivek'
  get "/happy", :to => "pages#happy"
  get "/kids", :to => "pages#kids"
  get "/sponsor", :to => "pages#sponsor"
  get "/sponsors", :to => "pages#sponsor"
  get "/usergroups", :to => "pages#usergroups"

  resources :favorites do
    collection do
      get 'thanks'
    end
  end

  resources :guests do
    collection do
      get 'thanks'
    end
  end

  resources :hosts do
    collection do
      get 'thanks'
    end
  end

  resources :speakers do
    collection do
      get 'thanks'
    end
  end

  resources :bohconf_sessions do
    collection do
      get 'thanks'
    end
    member do
      get 'tweet'
      post 'send_tweet'
    end
  end

  resources :twitter_accounts, :only => [:new, :edit, :update] do
    collection do
      get 'callback'
    end
  end
end

app/models/host.rb
class Host < ActiveRecord::Base
	validates_presence_of :name, :email, :phone

	scope :approved, where(:approved => true)
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  before_filter :authenticate, :only => [:index, :edit, :update, :destroy, :show]
  # GET /hosts
  # GET /hosts.json
  def index
    @hosts = Host.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hosts }
    end
  end

  # GET /hosts/1
  # GET /hosts/1.json
  def show
    @host = Host.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @host }
    end
  end

  # GET /hosts/new
  # GET /hosts/new.json
  def new
    @host = Host.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @host }
    end
  end

  # GET /hosts/1/edit
  def edit
    @host = Host.find(params[:id])
  end

  # POST /hosts
  # POST /hosts.json
  def create
    @host = Host.new(params[:host])

    respond_to do |format|
      if @host.save
        AdminMailer.submission(@host).deliver
        format.html { redirect_to thanks_hosts_url }
        format.json { render json: @host, status: :created, location: @host }
      else
        format.html { render action: "new" }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hosts/1
  # PUT /hosts/1.json
  def update
    @host = Host.find(params[:id])

    respond_to do |format|
      if @host.update_attributes(params[:host])
        format.html { redirect_to @host, notice: 'Host was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hosts/1
  # DELETE /hosts/1.json
  def destroy
    @host = Host.find(params[:id])
    @host.destroy

    respond_to do |format|
      format.html { redirect_to hosts_url }
      format.json { head :no_content }
    end
  end
end

app/views/hosts/_form.html.erb
<%= form_for(@host, :html => {:class => 'form-horizontal'}) do |f| %>
  <% if @host.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@host.errors.count, "error") %> prohibited this host from being saved:</h2>

      <ul>
      <% @host.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="span6">
      <div class="control-group">
        <%= f.label :name %>
        <div class="controls">
          <%= f.text_field :name %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :email %>
        <div class="controls">
          <%= f.text_field :email %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :phone %>
        <div class="controls">
          <%= f.text_field :phone %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :twitter %>
        <div class="controls">
          <div class="input-prepend">
            <span class="add-on">@</span>
            <%= f.text_field :twitter, :class => 'span2' %>
          </div>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :address1, 'Address' %>
        <div class="controls">
          <%= f.text_field :address1 %><br />
          <%= f.text_field :address2 %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :zip %>
        <div class="controls">
          <%= f.text_field :zip %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :number_of_guests, 'Number of guests you can host' %>
        <div class="controls">
          <%= f.select :number_of_guests, (1..10) %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :description %>
        <div class="controls">
          <%= f.text_area :description, :rows => 5 %>
          <p class="help-block">Tell us a little bit about your place.</p>
        </div>
      </div>

      <div class="form-actions">
        <%= f.submit 'Submit', :class => 'btn btn-primary' %>
      </div>
    </div>

    <div class="span6">
      <p>Think of it has AirB&B except you'll actually have something in common.</p>
      <p>When we find guests that might be a good match, we'll contact you with their details and give you a chance to vet before confirming anything.</p>
    </div>
  </div>

  
<% end %>

app/views/hosts/edit.html.erb
<div class="details">
    <h1>Editing host</h1>

    <%= render 'form' %>

    <%= link_to 'Show', @host %> |
    <%= link_to 'Back', hosts_path %>
</div>

app/views/hosts/index.html.erb
<div class="details">
    <h1>Listing hosts</h1>

    <table>
      <tr>
        <th>Name</th>
        <th>Address1</th>
        <th>Address2</th>
        <th>City</th>
        <th>State</th>
        <th>Zip</th>
        <th>Phone</th>
        <th>Number of guests</th>
        <th>Number of guests remaining</th>
        <th>Description</th>
        <th>Email</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

    <% @hosts.each do |host| %>
      <tr>
        <td><%= host.name %></td>
        <td><%= host.address1 %></td>
        <td><%= host.address2 %></td>
        <td><%= host.city %></td>
        <td><%= host.state %></td>
        <td><%= host.zip %></td>
        <td><%= host.phone %></td>
        <td><%= host.number_of_guests %></td>
        <td><%= host.number_of_guests_remaining %></td>
        <td><%= host.description %></td>
        <td><%= host.email %></td>
        <td><%= link_to 'Show', host %></td>
        <td><%= link_to 'Edit', edit_host_path(host) %></td>
        <td><%= link_to 'Destroy', host, confirm: 'Are you sure?', method: :delete %></td>
      </tr>
    <% end %>
    </table>

    <br />

    <%= link_to 'New Host', new_host_path %>
</div>

app/views/hosts/new.html.erb
<div class="details">
    <h1>Offer to Host an Attendee</h1>

    <%= render 'form' %>
</div>

app/views/hosts/show.html.erb
<div class="details">
  <p id="notice"><%= notice %></p>

  <p>
    <b>Name:</b>
    <%= @host.name %>
  </p>

  <p>
    <b>Address1:</b>
    <%= @host.address1 %>
  </p>

  <p>
    <b>Address2:</b>
    <%= @host.address2 %>
  </p>

  <p>
    <b>City:</b>
    <%= @host.city %>
  </p>

  <p>
    <b>State:</b>
    <%= @host.state %>
  </p>

  <p>
    <b>Zip:</b>
    <%= @host.zip %>
  </p>

  <p>
    <b>Phone:</b>
    <%= @host.phone %>
  </p>

  <p>
    <b>Number of guests:</b>
    <%= @host.number_of_guests %>
  </p>

  <p>
    <b>Number of guests remaining:</b>
    <%= @host.number_of_guests_remaining %>
  </p>

  <p>
    <b>Description:</b>
    <%= @host.description %>
  </p>

  <p>
    <b>Email:</b>
    <%= @host.email %>
  </p>


  <%= link_to 'Edit', edit_host_path(@host) %> |
  <%= link_to 'Back', hosts_path %>
</div>

app/views/hosts/thanks.html.erb
<div class="details">
    <h1>Thanks!</h1>

    <p>We'll be in touch soon to work out the details.</p>

    <p>If you have any questions, get in touch with <%= mail_to 'chapambrose@gmail.com' %>.</p>
</div>