config/routes.rb
Railsconf::Application.routes.draw do

  root :to => "pages#index"
  get "/bohconf", :to => "bohconf_sessions#index"
  get "/boh", :to => "bohconf_sessions#index"
  get "/bohconf_soon", :to => "bohconf_sessions#soon", :as => 'bohconf_sessions_soon'
  get "/boh/:id", :to => "bohconf_sessions#show", :as => "boh_short"
  get "/boh/:id/tweet", :to => "bohconf_sessions#tweet"
  get "/boh/:id/edit", :to => "bohconf_sessions#edit"
  get "/ignite", :to => "pages#ignite"
  get "/talk", :to => "pages#talk"
  get "/stay", :to => "pages#stay"
  get "/5k", :to => "pages#fivek", :as => 'fivek'
  get "/happy", :to => "pages#happy"
  get "/kids", :to => "pages#kids"
  get "/sponsor", :to => "pages#sponsor"
  get "/sponsors", :to => "pages#sponsor"
  get "/usergroups", :to => "pages#usergroups"

  resources :favorites do
    collection do
      get 'thanks'
    end
  end

  resources :guests do
    collection do
      get 'thanks'
    end
  end

  resources :hosts do
    collection do
      get 'thanks'
    end
  end

  resources :speakers do
    collection do
      get 'thanks'
    end
  end

  resources :bohconf_sessions do
    collection do
      get 'thanks'
    end
    member do
      get 'tweet'
      post 'send_tweet'
    end
  end

  resources :twitter_accounts, :only => [:new, :edit, :update] do
    collection do
      get 'callback'
    end
  end
end

app/models/bohconf_session.rb
class BohconfSession < ActiveRecord::Base
	validates_presence_of :title, :host_email

	scope :approved, where(:hide => false)
end

app/controllers/bohconf_sessions_controller.rb
class BohconfSessionsController < ApplicationController
  layout 'bohconf'
  before_filter :authenticate, :only => [:destroy, :write_tweet, :send_tweet]
  before_filter :authorized_to_edit_bohconf_session, :only => [:edit, :update]

  def index
    # show me sessions that have started in the last hour
    # or will start in the next 20 minutes
    # that havent ended yet
    @sessions = BohconfSession.approved.
      order('starts_at')

    
    redirect_to bohconf_sessions_soon_path if @sessions.empty?
  end

  def soon
    @sessions = BohconfSession.approved.
      where('starts_at >= ?', Time.now).
      where('ends_at >= ?', Time.now).
      order('starts_at')

    @sessions = @sessions.where('session_type = ?', params[:session_type]) if params[:session_type].present?
  end

  def show
    @bohconf_session = BohconfSession.find(params[:id])

    render :layout => 'bohconf'
  end

  def new
    @bohconf_session = BohconfSession.new
  end

  def edit

  end

  def create
    @bohconf_session = BohconfSession.new(params[:bohconf_session])
    @bohconf_session.starts_at = params[:bohconf_session][:starts_at].to_time
    @bohconf_session.ends_at = params[:bohconf_session][:ends_at].to_time

    @bohconf_session.token = SecureRandom.hex(10)

    if @bohconf_session.save
      AdminMailer.submission(@bohconf_session).deliver
      UserMailer.bohconf_session_submitted(@bohconf_session).deliver
      if @admin
        redirect_to tweet_bohconf_session_url(@bohconf_session)
      else
        redirect_to thanks_bohconf_sessions_url
      end
    else
      render :new
    end
  end

  # PUT /bohconf_sessions/1
  # PUT /bohconf_sessions/1.json
  def update
    @bohconf_session = BohconfSession.find(params[:id])
    params[:bohconf_session][:starts_at] = params[:bohconf_session][:starts_at].to_time
    params[:bohconf_session][:ends_at] = params[:bohconf_session][:ends_at].to_time
    if @bohconf_session.update_attributes(session_params)
      redirect_to bohconf_path, notice: 'Session was successfully updated.'
    end
  end

  def destroy
    @bohconf_session = BohconfSession.find(params[:id])
    @bohconf_session.destroy
  end

  def tweet
    @bohconf_session = BohconfSession.find(params[:id])
  end

  def send_tweet
    @bohconf_session = BohconfSession.find(params[:id])
    @tweet = bohconf_twitter_account.post(params[:tweet_body])
    if @tweet
      redirect_to @bohconf_session, notice: 'Tweeted!'
    else
      render :write_tweet
    end
  end

  private
  def authorized_to_edit_bohconf_session
    @bohconf_session = BohconfSession.find(params[:id])
    unless (params[:token].present? && @bohconf_session.token == params[:token]) || authenticate
      redirect_to(bohconf_sessions_path, notice: "Looks like you're not authorized.") && return
    end
  end
  def session_params
    if @admin
      params[:bohconf_session]
    else
      p = params[:bohconf_session]
      p.delete(:hide)
      p
    end
  end
end

app/helpers/bohconf_sessions_helper.rb
module BohconfSessionsHelper
	def session_time(time)
		options = []

		if Time.zone.now < Time.zone.parse("2012-04-23 10:00pm")
			(9..11).each do |i|
				options << ["Monday #{i}:00am", Time.zone.parse("2012-04-23 #{i}:00am")]
				options << ["Monday #{i}:30am", Time.zone.parse("2012-04-23 #{i}:30am")]
			end
			options << ["Monday 12:00pm", Time.zone.parse("2012-04-23 12:00pm")]
			options << ["Monday 12:30pm", Time.zone.parse("2012-04-23 12:30pm")]
			(1..10).each do |i|
				options << ["Monday #{i}:00pm", Time.zone.parse("2012-04-23 #{'%02d' % (i+12)}:00pm")]
				options << ["Monday #{i}:30pm", Time.zone.parse("2012-04-23 #{'%02d' % (i+12)}:30pm")]
			end
		end

		if Time.zone.now < Time.zone.parse("2012-04-24 9:00pm")
			(9..11).each do |i|
				options << ["Tuesday #{i}:00am", Time.zone.parse("2012-04-24 #{i}:00am")]
				options << ["Tuesday #{i}:30am", Time.zone.parse("2012-04-24 #{i}:30am")]
			end
			options << ["Tuesday 12:00pm", Time.zone.parse("2012-04-24 12:00pm")]
			options << ["Tuesday 12:30pm", Time.zone.parse("2012-04-24 12:30pm")]
			(1..9).each do |i|
				options << ["Tuesday #{i}:00pm", Time.zone.parse("2012-04-24 #{'%02d' % (i+12)}:00pm")]
				options << ["Tuesday #{i}:30pm", Time.zone.parse("2012-04-24 #{'%02d' % (i+12)}:30pm")]
			end
		end

		(9..11).each do |i|
			options << ["Wednesday #{i}:00am", Time.zone.parse("2012-04-25 #{i}:00am")]
			options << ["Wednesday #{i}:30am", Time.zone.parse("2012-04-25 #{i}:30am")]
		end
		options << ["Wednesday 12:00pm", Time.zone.parse("2012-04-25 12:00pm")]
		options << ["Wednesday 12:30pm", Time.zone.parse("2012-04-25 12:30pm")]
		(1..3).each do |i|
			options << ["Wednesday #{i}:00pm", Time.zone.parse("2012-04-25 #{'%02d' % (i+12)}:00pm")]
			options << ["Wednesday #{i}:30pm", Time.zone.parse("2012-04-25 #{'%02d' % (i+12)}:30pm")]
		end

		options_for_select(options, (time.strftime("%F %H:%M:00 -0500") rescue Time.now.strftime("%F %H:%M:00 -0500")))
	end
end

app/views/bohconf_sessions/_form.html.erb
 <%= form_for(@bohconf_session) do |f| %>

  <% if @bohconf_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bohconf_session.errors.count, "error") %> prohibited this bohconf_session from being saved:</h2>

      <ul>
      <% @bohconf_session.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <fieldset>
      <div class="control-group clearfix">
        <label for="">Host Name</label>
        <%= f.text_field :host_name, :placeholder => "first and last name" %>
      </div>
      <div class="control-group clearfix">
        <label for="">Email</label>
        <%= f.text_field :host_email, :placeholder => "example@example.com" %>
      </div>
      <div class="control-group clearfix">
        <label for="">Twitter</label>
        <%= f.text_field :host_twitter, :placeholder => "username (no @)" %>
      </div>
      <div class="control-group clearfix">
        <label for="">Topic</label>
        <%= f.text_field :title, :placeholder => "My Awesome Session!" %>
      </div>
      <div class="control-group clearfix">
        <label for="">Description</label>
        <%= f.text_area :abstract, :rows => 4, :placeholder => '(optional)' %>
      </div>
      <div class="control-group clearfix">
        <label for="">Type</label>
        <%= f.select :session_type, options_for_select(['hack', 'talk', 'bof'], @bohconf_session.session_type) %>
      </div>
      <div class="control-group clearfix">
        <label for="">Starts</label>
        <%= f.select :starts_at, session_time(@bohconf_session.starts_at) %>
      </div>
       <p class="form-notes">We only have space for 1 talk at a time. If you're submitting a talk <%= link_to "make sure you're not overlapping", bohconf_sessions_soon_path(:session_type => 'talk') %>.</p><br />
      <div class="control-group clearfix">
        <label for="">Ends</label>
        <%= f.select :ends_at, session_time(@bohconf_session.ends_at) %>
      </div>
      <div class="form-actions">
        <%= hidden_field_tag :token, params[:token] %>
        <button class="" type="submit">Blammo</button>
      </div>
    </fieldset>
  <% end %>

app/views/bohconf_sessions/_session.html.erb
<section id="latest-talk" class="content">
  <h1><%= session.starts_at.strftime("%a %l:%M%p") %> - <%= session.ends_at.strftime("%l:%M%p") %></h1>
  <article class="talk">
    <div class="host clearfix">
      <a class="host-thumb" href="<%= 'http://twitter.com/' + session.host_twitter if session.host_twitter.present? %>" target="_blank">
        <%= image_tag("http://api.twitter.com/1/users/profile_image/#{session.host_twitter}?size=normal", :size => "48x48") %>
      </a>
      <b class="<%= session.session_type %>"><%= session.session_type.upcase %></b>
      <h2><%= link_to session.title, boh_short_path(session) %></h2>
      <h3><em>by</em> <%= session.host_name %></h3>
      <% if @admin %>
        <%= link_to 'edit', edit_bohconf_session_path(session) %>
      <% end %>
    </div>
    <p class="description">
      <%= auto_link session.abstract %>
    </p>
  </article>
</section> <!-- /#latest-talk -->

app/views/bohconf_sessions/edit.html.erb
<section id="request-form" class="content">
  <h1>Edit Session</h1>
  <%= render 'form' %>
</section> <!-- /#latest-tweet -->

app/views/bohconf_sessions/index.html.erb
<h1>Listing bohconf_sessions</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Abstract</th>
    <th>Host name</th>
    <th>Host email</th>
    <th>Host twitter</th>
    <th>Host bio</th>
    <th>Starts at</th>
    <th>Ends at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bohconf_sessions.each do |bohconf_session| %>
  <tr>
    <td><%= bohconf_session.title %></td>
    <td><%= bohconf_session.abstract %></td>
    <td><%= bohconf_session.host_name %></td>
    <td><%= bohconf_session.host_email %></td>
    <td><%= bohconf_session.host_twitter %></td>
    <td><%= bohconf_session.host_bio %></td>
    <td><%= bohconf_session.starts_at %></td>
    <td><%= bohconf_session.ends_at %></td>
    <td><%= link_to 'Show', bohconf_session %></td>
    <td><%= link_to 'Edit', edit_bohconf_session_path(bohconf_session) %></td>
    <td><%= link_to 'Destroy', bohconf_session, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bohconf session', new_bohconf_session_path %>

app/views/bohconf_sessions/new.html.erb
<section id="request-form" class="content">
  <h1>Add A Session</h1>
  <%= render 'form' %>
</section> <!-- /#latest-tweet -->

app/views/bohconf_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<%= render :partial => 'bohconf_sessions/session', :locals => {:session => @bohconf_session} %>

app/views/bohconf_sessions/soon.html.erb
<% @sessions.each do |session| %>
  <%= render :partial => 'bohconf_sessions/session', :locals => {:session => session} %>
<% end %>

app/views/bohconf_sessions/thanks.html.erb
<section class="content">
  <h1>Thanks!</h1>
  <p>Your session has been added.</p>
  <p>If you have any questions, get in touch with <%= mail_to 'railsconf@austinonrails.org' %>.</p>
</section>

app/views/bohconf_sessions/tweet.html.erb
<section class="content">
	<h1>Tweet about BohConf Session</h1>

	<%= form_tag(send_tweet_bohconf_session_path(@bohconf_session)) do %>
		<%= text_area_tag :tweet_body, "##{@bohconf_session.session_type} #{'@'+@bohconf_session.host_twitter unless @bohconf_session.host_twitter.blank?} \"#{@bohconf_session.title}\" #{@bohconf_session.starts_at.strftime("%a %l:%M%p")} #{boh_short_url(@bohconf_session)}", :cols => 50, :rows => 5 %>
		<div class="charCount">
			<span id="characters-left" class="characters-left"></span> characters left
		</div>
		<%= submit_tag 'Tweeeet!', :class => 'tweeeet' %>
	<% end %>

	<script type="text/javascript">
		$(document).ready(function() {
			left = 140 - $('#tweet_body').val().length;
			$('#characters-left').text(left);
			
			$('#tweet_body').keyup(function() {
				left = 140 - $('#tweet_body').val().length;
				$('#characters-left').text(left);
			})
		})
	</script>
</section>